// <auto-generated />
using System;
using EXE201_Tutor_Web_API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EXE201_Tutor_Web_API.Migrations
{
    [DbContext(typeof(Exe201_Tutor_Context))]
    [Migration("20240217024448_Create_Exe_Database_17022024_9h37")]
    partial class Create_Exe_Database_17022024_9h37
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.Coursera", b =>
                {
                    b.Property<int>("CourseraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("CourseraId");

                    b.ToTable("Coursera");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.CourseraDetail", b =>
                {
                    b.Property<int>("CourseraDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseraId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("CourseraDetailId");

                    b.HasIndex("CourseraId");

                    b.ToTable("CourseraDetail");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.Mooc", b =>
                {
                    b.Property<int>("MoocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseraDetailId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MinScore")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("MoocId");

                    b.HasIndex("CourseraDetailId");

                    b.ToTable("Mooc");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.MoocDetail", b =>
                {
                    b.Property<int>("MoocDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MoocId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("MoocDetailId");

                    b.HasIndex("MoocId");

                    b.ToTable("MoocDetail");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.OnCourse", b =>
                {
                    b.Property<int>("OnCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CourseraId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OnCourseId");

                    b.HasIndex("CourseraId");

                    b.HasIndex("UserId");

                    b.ToTable("OnCourse");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.OnCourseDetail", b =>
                {
                    b.Property<int>("OnCourseDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CourseraDetailId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("OnCourseId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("OnCourseDetailId");

                    b.HasIndex("CourseraDetailId");

                    b.HasIndex("OnCourseId");

                    b.ToTable("OnCourseDetail");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.OnMooc", b =>
                {
                    b.Property<int>("OnMoocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateSuccess")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MoocId")
                        .HasColumnType("int");

                    b.Property<int?>("OnCourseDetailId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("OnMoocId");

                    b.HasIndex("MoocId");

                    b.HasIndex("OnCourseDetailId");

                    b.ToTable("OnMooc");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.OnMoocDetail", b =>
                {
                    b.Property<int>("OnMoocDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .HasColumnType("longtext");

                    b.Property<int?>("MoocDetailId")
                        .HasColumnType("int");

                    b.Property<int?>("OnMoocId")
                        .HasColumnType("int");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("OnMoocDetailId");

                    b.HasIndex("MoocDetailId");

                    b.HasIndex("OnMoocId");

                    b.ToTable("OnMoocDetail");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.CourseraDetail", b =>
                {
                    b.HasOne("EXE201_Tutor_Web_API.Entites.Coursera", "Coursera")
                        .WithMany("CourseraDetails")
                        .HasForeignKey("CourseraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coursera");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.Mooc", b =>
                {
                    b.HasOne("EXE201_Tutor_Web_API.Entites.CourseraDetail", "CourseraDetail")
                        .WithMany("Moocs")
                        .HasForeignKey("CourseraDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseraDetail");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.MoocDetail", b =>
                {
                    b.HasOne("EXE201_Tutor_Web_API.Entites.Mooc", "Mooc")
                        .WithMany("MoocDetails")
                        .HasForeignKey("MoocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mooc");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.OnCourse", b =>
                {
                    b.HasOne("EXE201_Tutor_Web_API.Entites.Coursera", "Coursera")
                        .WithMany("OnCourses")
                        .HasForeignKey("CourseraId");

                    b.HasOne("EXE201_Tutor_Web_API.Entites.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Coursera");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.OnCourseDetail", b =>
                {
                    b.HasOne("EXE201_Tutor_Web_API.Entites.CourseraDetail", "CourseraDetail")
                        .WithMany("OnCourseDetails")
                        .HasForeignKey("CourseraDetailId");

                    b.HasOne("EXE201_Tutor_Web_API.Entites.OnCourse", "OnCourse")
                        .WithMany("OnCourseDetails")
                        .HasForeignKey("OnCourseId");

                    b.Navigation("CourseraDetail");

                    b.Navigation("OnCourse");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.OnMooc", b =>
                {
                    b.HasOne("EXE201_Tutor_Web_API.Entites.Mooc", "Mooc")
                        .WithMany("OnMoocs")
                        .HasForeignKey("MoocId");

                    b.HasOne("EXE201_Tutor_Web_API.Entites.OnCourseDetail", "OnCourseDetail")
                        .WithMany("OnMoocs")
                        .HasForeignKey("OnCourseDetailId");

                    b.Navigation("Mooc");

                    b.Navigation("OnCourseDetail");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.OnMoocDetail", b =>
                {
                    b.HasOne("EXE201_Tutor_Web_API.Entites.MoocDetail", "MoocDetail")
                        .WithMany("OnMoocDetails")
                        .HasForeignKey("MoocDetailId");

                    b.HasOne("EXE201_Tutor_Web_API.Entites.OnMooc", "OnMooc")
                        .WithMany("OnMoocDetails")
                        .HasForeignKey("OnMoocId");

                    b.Navigation("MoocDetail");

                    b.Navigation("OnMooc");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.Coursera", b =>
                {
                    b.Navigation("CourseraDetails");

                    b.Navigation("OnCourses");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.CourseraDetail", b =>
                {
                    b.Navigation("Moocs");

                    b.Navigation("OnCourseDetails");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.Mooc", b =>
                {
                    b.Navigation("MoocDetails");

                    b.Navigation("OnMoocs");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.MoocDetail", b =>
                {
                    b.Navigation("OnMoocDetails");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.OnCourse", b =>
                {
                    b.Navigation("OnCourseDetails");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.OnCourseDetail", b =>
                {
                    b.Navigation("OnMoocs");
                });

            modelBuilder.Entity("EXE201_Tutor_Web_API.Entites.OnMooc", b =>
                {
                    b.Navigation("OnMoocDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
